---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"

- name: include release specific variables
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true

- name: include release specific tasks
  include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  ignore_errors: true

- name: groupadd
  group:
    name: "{{ bamboo_group }}"
    system: true
    state: "present"

- name: useradd
  user:
    name: "{{ bamboo_owner }}"
    group: "{{ bamboo_group }}"
    home: "{{ bamboo_home }}"
    shell: "/usr/sbin/nologin"
    system: true
    create_home: false
    state: "present"

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/lib/systemd/system" }
    - { dest: "/lib/systemd/system/bamboo.service.d" }
    - { dest: "{{ bamboo_download.dest | dirname }}" }
    - { dest: "{{ mysql_jdbc_download.dest | dirname }}" }
    - { dest: "{{ postgresql_jdbc_download.dest | dirname }}" }
    - dest: "{{ bamboo_catalina }}"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
    - dest: "{{ bamboo_catalina }}/bin"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
    - dest: "{{ bamboo_catalina }}/conf"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
    - dest: "{{ bamboo_home }}"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"

- name: download archive
  vars:
    ansible_python_interpreter: "python3"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
    mode: "{{ item.mode | default('0644') }}"
    timeout: 300
  loop:
    - "{{ bamboo_download }}"
    - "{{ mysql_jdbc_download }}"
    - "{{ postgresql_jdbc_download }}"
  register: get_url_result
  until: get_url_result is succeeded

- name: unarchive package
  shell: |
    set -o pipefail
    rm -rf {{ bamboo_catalina }} \
      && mkdir -p {{ bamboo_catalina }}
    cd {{ bamboo_catalina }}
    TMP_DIR="$(mktemp -d)" \
      && tar -zx -C $TMP_DIR -f {{ bamboo_download.dest }} \
      && cp -rfT $TMP_DIR/* . \
      && rm -rf $TMP_DIR
    cd {{ bamboo_catalina }}/lib
    rm -rf *mysql*.jar
    TMP_DIR="$(mktemp -d)" \
      && tar -zx -C $TMP_DIR -f {{ mysql_jdbc_download.dest }} \
      && mv $TMP_DIR/*/*mysql*-bin.jar . \
      && rm -rf $TMP_DIR
    cd {{ bamboo_catalina }}/lib
    rm -rf *postgresql*.jar
    cp {{ postgresql_jdbc_download.dest }} .
    chown -Rf {{ bamboo_owner }}:{{ bamboo_group }} {{ bamboo_catalina }}
    chmod 0755 \
      {{ bamboo_catalina }} \
      {{ bamboo_catalina }}/bin \
      {{ bamboo_catalina }}/conf
  args:
    executable: "/bin/bash"
  when: get_url_result is changed
  notify:
    - bamboo | systemctl daemon-reload
    - bamboo | systemctl restart bamboo.service

- name: copy templates
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: "/lib/systemd/system/bamboo.service" }
    - dest: "{{ bamboo_catalina }}/bin/setenv.sh"
      src: "./templates/opt/atlassian/bamboo/bin/setenv.sh.j2"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
      mode: "0755"
    - dest: "{{ bamboo_catalina }}/conf/server.xml"
      src: "./templates/opt/atlassian/bamboo/conf/server.xml.j2"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
  notify:
    - bamboo | systemctl daemon-reload
    - bamboo | systemctl restart bamboo.service

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/lib/systemd/system/bamboo.service" }
    - dest: "{{ bamboo_catalina }}/bin/setenv.sh"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
      mode: "0755"
    - dest: "{{ bamboo_catalina }}/conf/server.xml"
      owner: "{{ bamboo_owner }}"
      group: "{{ bamboo_group }}"
  notify:
    - bamboo | systemctl daemon-reload
    - bamboo | systemctl restart bamboo.service

- name: systemctl start bamboo.service
  service:
    name: "bamboo.service"
    state: "started"
    enabled: true
  changed_when: false
  ignore_errors: true

- name: flush handlers
  meta: flush_handlers
